apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstjobcompany
  labels:
    app: firstjobcompany
spec:
  replicas: 1
  template:
    metadata:
      name: firstjobcompany
      labels:
        app: firstjobcompany
    spec:
      containers:
        - name: firstjobcompany
          image: paanja2020/jobcompanyappimage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always 
  selector:
    matchLabels:
      app: firstjobcompany 
